version: "3.9"

services:
  lb:
    build:
      context: ./load_balancer
      dockerfile: Dockerfile
    tty: true
    ports:
      - '80:80'
    volumes:
      - './load_balancer:/usr/share/nginx/html'

    networks:
      app-network:
        ipv4_address: 192.168.10.2
    depends_on:
      - mariadb
  y_appo_front:
    build:
      context: ./y_appoint/gecko_front
      dockerfile: Dockerfile
    environment:
      timezone: 'Asia/Tokyo'
    tty: true
    ports:
      - '122:22'
      - '3000:3000'
    volumes:
      - './y_appoint/gecko_front/app:/app'
    depends_on:
      - mariadb

    networks:
      app-network:
        ipv4_address: 192.168.10.3

  y_appo_back:
    build:
      context: ./y_appoint/gecko_back
      dockerfile: Dockerfile
    environment:
      timezone: 'Asia/Tokyo'
    tty: true
    ports:
      - '222:22'
      - '9000:8080'
    volumes:
      - './y_appoint/gecko_back/app:/app'

    networks:
      app-network:
        ipv4_address: 192.168.10.4

    depends_on:
      - mariadb

  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      timezone: 'Asia/Tokyo'
    tty: true
    ports:
      - '3308:3306'
    volumes:
      - './mariadb/data:/var/lib/mysql'
    restart: always
    networks:
      app-network:
        ipv4_address: 192.168.10.5

networks:
  app-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
